### ISSUE TITLE
Verify advice/letter content testing tool has all variations and that content is as expected

### ISSUE THREAD

**Issue by AlexLexo** [AlexLexo/my-legal-helper#1]
The testing tool's output is now ready to be checked on the [VC sheet](https://docs.google.com/spreadsheets/d/1-Z8UJJaLsRHd3yPep0QZagnL3q6jqIcYQ4DVyN3ZxjQ/edit#gid=144603983):

- There is one long column with grouped answers, advice and letters.
- Both the letter and the advice share the same answers.
- The key for the letter is the first item eg 'injuredByAnimalLetter'.
- The key for the advice is the second item eg 'animal'.
- All injuredByPed answers are at the end.

Please check that the tool has all required variations of advice and letters and that the content is as expected.

All errors and changes should be noted in full on the VC sheet with a red background.

**Comment by ojeffcott** [comment]
Test
